version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Running Tests"
      - run: npm install
      - run: npm test
  pretest:
    docker:
        - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "PreTestRuning...."
workflows:
  version: 2
  build_and_test_and_lint:
    jobs:
      - build
      - pretest
      - test:
          requires:
            - pretest